local task = require("core.tasks")
vim.keymap.set("n", "<leader>rr", function()
    task.run("go:run")
end)
vim.keymap.set("n", "<leader>rb", function()
    task.run("go:build")
end)
vim.keymap.set("n", "<leader>tt", function()
    task.run("go:test")
end)
vim.keymap.set("n", "<leader>tb", function()
    task.run("go:bench")
end)
vim.keymap.set("n", "<leader>tc", function()
    task.run("go:coverage")
end)
vim.keymap.set("n", "<leader>mt", function()
    task.run("go:tidy")
end)
vim.keymap.set("n", "<leader>mg", function()
    task.run("go:generate")
end)
